# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20171122_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(null=True, verbose_name='Текст ответа'),
        ),
    ]
