# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 06:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180216_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст ответа'),
        ),
    ]
