# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20180326_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Specify values from 1 to 100, where 100 has the highest priority. If you do not specify a priority, it will be 0', verbose_name='Display priority'),
        ),
        migrations.AlterField(
            model_name='question',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Specify values from 1 to 100, where 100 has the highest priority. If you do not specify a priority, it will be 0', verbose_name='Display priority'),
        ),
    ]
