# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:39
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет отображения')),
                ('name', models.CharField(max_length=50, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет отображения')),
                ('name', models.CharField(max_length=50, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет отображения')),
                ('name', models.CharField(max_length=50, verbose_name='Название уровня')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровни',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет отображения')),
                ('name', models.CharField(max_length=100, verbose_name='Направление направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Приоритет отображения')),
                ('name', models.CharField(max_length=50, verbose_name='Название вакансии')),
                ('text_main', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст описания для отображения на главной')),
                ('text_inner', ckeditor.fields.RichTextField(verbose_name='Текст описания внутри вакансии')),
                ('text_experience', ckeditor.fields.RichTextField(verbose_name='Текст "Опыт и знания')),
                ('text_desc', ckeditor.fields.RichTextField(verbose_name='Описание работы')),
                ('text_qualifying', ckeditor.fields.RichTextField(verbose_name='Отборочный цикл')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горячая вакансия')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликована')),
                ('cities', smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='country', chained_model_field='country', horizontal=True, to='vacancies.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Country', verbose_name='Страна')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Experience', verbose_name='Уровень')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Profile', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='vacancies.Country', verbose_name='Страна'),
        ),
    ]
