# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Путь'),
        ),
    ]
