# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20171122_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название направления'),
        ),
    ]
