# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 12:26
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_auto_20180111_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='cities',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', horizontal=True, to='vacancies.City'),
        ),
    ]
