# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20180129_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_in_case',
            field=models.CharField(default='', max_length=50, verbose_name='Название страны в родительном падеже'),
        ),
    ]
