# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_country_name_in_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Путь'),
        ),
    ]
