# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_auto_20180216_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='На главной'),
        ),
    ]
