# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 08:20
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


def update_slugs(apps, schema_editor):
    models = ('Country', 'City', 'Profile', 'Experience')
    for model in models:
        model_obj = apps.get_model('vacancies', model)
        db_alias = schema_editor.connection.alias
        for obj in model_obj.objects.using(db_alias).filter(slug__isnull=True):
            obj.save(update_fields=['name', 'slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20180216_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True, verbose_name='Путь'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True, verbose_name='Путь'),
        ),
        migrations.AddField(
            model_name='experience',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True, verbose_name='Путь'),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True, verbose_name='Путь'),
        ),
        migrations.RunPython(update_slugs),
    ]
