# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 17:26
from __future__ import unicode_literals

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20180223_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('-priority', 'name'), 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-priority', 'name'), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-priority', 'name'), 'verbose_name': 'Level experience', 'verbose_name_plural': 'Levels experience'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-priority', 'name'), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ('-priority', 'name'), 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='vacancies.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='city',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Specify values from 1 to 100, where 100 has the highest priority. If you do not specify a priority, it will be 0', verbose_name='Display priority'),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Country name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_in_case',
            field=models.CharField(default='', max_length=50, verbose_name='Country name in parental case'),
        ),
        migrations.AlterField(
            model_name='country',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Specify values from 1 to 100, where 100 has the highest priority. If you do not specify a priority, it will be 0', verbose_name='Display priority'),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Level experience name'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Specify values from 1 to 100, where 100 has the highest priority. If you do not specify a priority, it will be 0', verbose_name='Display priority'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Profile name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Specify values from 1 to 100, where 100 has the highest priority. If you do not specify a priority, it will be 0', verbose_name='Display priority'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, null=True, populate_from='name', unique=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Experience', verbose_name='Level experience'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Show on main'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is published'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Vacancy name'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Specify values from 1 to 100, where 100 has the highest priority. If you do not specify a priority, it will be 0', verbose_name='Display priority'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.Profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='text_desc',
            field=ckeditor.fields.RichTextField(verbose_name='Work description text'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='text_experience',
            field=ckeditor.fields.RichTextField(verbose_name='Description text of experience and knowledge'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='text_inner',
            field=ckeditor.fields.RichTextField(verbose_name='Description text for display on vacancy page'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='text_main',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description text for display on main page'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='text_qualifying',
            field=ckeditor.fields.RichTextField(verbose_name='Description text for qualifying'),
        ),
    ]
